services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=trivia_user
      - POSTGRES_PASSWORD=trivia_pass
      - POSTGRES_DB=trivia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build: ./frontend
    ports:
      - "3008:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ./backend
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=trivia_user
      - PG_PASSWORD=trivia_pass
      - PG_DB=trivia_db
    depends_on:
      - db

volumes:
  postgres_data:
