apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-trivia.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
  PG_PASSWORD: {{ .Values.backend.env.PG_PASSWORD | quote }}
  ADMIN_SEED_PASSWORD: {{ .Values.backend.env.ADMIN_SEED_PASSWORD | quote }}
  SMTP_PASS: {{ .Values.backend.env.SMTP_PASS | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.backend.env.DISCORD_CLIENT_SECRET | quote }}
  DISCORD_BOT_API_TOKEN: {{ .Values.backend.env.DISCORD_BOT_API_TOKEN | quote }}
{{- if .Values.discordBot.enabled }}
  DISCORD_BOT_TOKEN: {{ .Values.discordBot.env.DISCORD_TOKEN | quote }}
{{- end }}
